# Generated by Django 4.0.6 on 2022-07-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('support_date', models.DateField()),
                ('support_time', models.CharField(choices=[('بین ساعت 15 تا 16', 'بین ساعت 15 تا 16'), ('بین ساعت 16 تا 17', 'بین ساعت 16 تا 17'), ('بین ساعت 18 تا 20', 'بین ساعت 18 تا 20')], max_length=100)),
            ],
            options={
                'db_table': 'support',
            },
        ),
    ]
