# Generated by Django 4.0.6 on 2022-07-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0002_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
