# Generated by Django 4.0.6 on 2022-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0003_alter_support_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='support_date',
            field=models.DateField(null=True),
        ),
    ]
